### ISSUE TITLE
is this intended to be a library or a shadcn copy/paste style approach?

### ISSUE THREAD

**Issue by liorix** [bluzky/salad_ui#11]
First, I want to say that I love your work. I've been hoping to see someone develop a project like this for Live View. I do have a question about this library. Shadcn mentions:

"This is NOT a component library. It's a collection of re-usable components that you can copy and paste into your apps.

What do you mean by not a component library?
I mean you do not install it as a dependency. It is not available or distributed via npm.

Pick the components you need. Copy and paste the code into your project and customize it to your needs. The code is yours."

Are you planning to take a similar approach?

**Comment by bluzky** [comment]
Hi @liorix,

When I started this project, my idea is to wrap all necessary for a component (tag, js)  in a single file so you can copy which component you need. That way, you can easily customize the components of your choice. So you can see I try to avoid extra js/hook.
Of course, you can use it as a component library if you are ok with pre-defined style.

**Comment by liorix** [comment]
Thanks @bluzky. Looking forward to giving it a try.

**Comment by domnantas** [comment]
I think this should be clearly explained in README/storybook. Right now the only suggested approach is using the component library as an installable dependency.
