### ISSUE TITLE
Switch: adding liveview binding has no effect

### ISSUE THREAD

**Issue by utopos** [bluzky/salad_ui#32]
Hello!

Firstly great job on porting this great library to LiveVIew. A quick question: how can I effectively attach a binding to the component (i.e. phx-click or phx-change)?

Best,
Jakub

**Comment by bluzky** [comment]
Sorry for late response.
For basic components, you can bind event as usual:
```html
          <.button phx-click={JS.push("update")}>
            Close from back-end
          </.button>
```

For other components like sheet, dialog, etc., they don't allow event binding.
If you have any specific issue, pls open another one.
