### ISSUE TITLE
JsxToHeex not working

### ISSUE THREAD

**Issue by geofflangenderfer** [bluzky/salad_ui#37]
did you remove this? The demo doesn't convert jsx to heex. 

Could you add some more color on this functionality? I'm interested in adopting this library 

https://salad-storybook.fly.dev/examples/convert_shadui

**Comment by bluzky** [comment]
@geofflangenderfer after pasting jsx code to the input textarea, click outside the textarea. It works on blur event. I'm thinking of adding a button
