### ISSUE TITLE
CLI to generate de components in the project 

### ISSUE THREAD

**Issue by andresgutgon** [bluzky/salad_ui#39]
## What?
Maybe this is already possible but reading the readme looks the idea is that components live in the package and not in my project so I can't modify it. Is that tre case?

Anyway awesome work. Today I just started playing with elixir and this package look great!

**Comment by bluzky** [comment]
Thanks for your suggestion, currently you have to copy and setup manually to copy component to your project.
Maybe I will add document to setup first. Build CLI would take much time.

**Comment by andresgutgon** [comment]
Cool thanks for the response!
I'm checking the code and trying to understand how hard would be to do the CLI. If I understand correctly the parts here are

1. Tailwind + Tailwind config + Tailwind colors
2. The components

I think shadcn let users to configure tailwind and colors on their end and the CLI does the generation of the components. 

Wouldn't be possible to have Phoenix-like generators inside this package that generate the components? I have to look more into this because I think a cli approach is awesome in my experience with shadcn js version

**Comment by bluzky** [comment]
Yeah. The hard part is how to patch existing files: tailwind.config.js, config.exs, etc.
Command to copy/install a component is pretty easy

**Comment by andresgutgon** [comment]
> Yeah. The hard part is how to patch existing files: tailwind.config.js, config.exs, etc.

That's true, I didn't though about it. Maybe is already a solved problem. This can be done the nice way with a AST or the hacky way with regex. But no idea. Also never worked with elixir before other than toy projects. 

Anyway thanks for your time, I might keep thinking on this but feel free to close this issue : )

**Comment by bluzky** [comment]
Thanks. It's a part of my plan. So I'll close when it's done

**Comment by forest** [comment]
Great work on the project. Going to give it a try.

You might look at using https://github.com/ash-project/igniter to make setup really east for people. It can install and patch files in an existing project. Can probably even use it to install (copy) components into a project.

**Comment by selenil** [comment]
Hello!

I've been doing some research, and I believe I can solve the issue of patching files using regex. There are essentially four files to patch (config.exs, tailwind.config.js, app.css, and app.js), and most of them aren't too complicated. I checked out [igniter](https://github.com/ash-project/igniter), but from what I can tell, it only patches Elixir files, not other types. Given the setup of this library, I think a regex-based patching method could be a more accurate, though I'm interested in hearing other ideas if anyone has a different solution.

I'm open to contribute to this project building the CLI. We could have two mix tasks, `init` and `add`, one for automate all the setup proccess to use the library and the other for add components, respectively. The `init` task could handle patching the necessary files, and the `add` task could use EEX templates to insert components into the user's project with the correct module names.

@bluzky, please let me know if this approach seems appropriate. If so, I'll go ahead and open a PR.

Also, thank you very much for the amazing work on this library.

**Comment by bluzky** [comment]
@selenil I totally agree with you. I used to have the same idea.
Would love to see your PR

**Comment by bluzky** [comment]
Close this due to implemented in #54
