### ISSUE TITLE
REQUEST: Complete LiveView Form implementation example

### ISSUE THREAD

**Issue by jasur-boswell** [bluzky/salad_ui#46]
Hi @bluzky!

Would it be possible for you to add a complete LiveView form example with different types of inputs (input, textarea, select, checkbox) using the Salad UI components? It would be really helpful for more novice Elixir programmers to get a more complete example of how to implement forms using your components.

**Comment by bluzky** [comment]
@jasur-boswell sure, I'll add another example on the storybook. I'll ping you when it's done

**Comment by bluzky** [comment]
@jasur-boswell  here is a demo form. 
https://github.com/bluzky/salad_storybook/blob/main/storybook/examples/form_demo.story.exs
If you have any question, feel free to ask me
