### ISSUE TITLE
Chart component proposal

### ISSUE THREAD

**Issue by selenil** [bluzky/salad_ui#63]
Hello.

I think we could implement a chart component using a strategy that combines [Chart.js](https://www.chartjs.org/docs/latest/) for efficiently rendering charts with Phoenix LiveView to manage the data, configurations, and updates. The two would communicate through Phoenix LiveView's hooks feature.

Here's my proposal to implement the chart component.

Users create a chart by defining a `live_component` that renders the chart's markup. This component handles data collection, configuration, and automatic updates on data changes. `SaladUI` will provide the building blocks for creating charts as components.

The implementation centers around two main components: `chart_container` and `chart`.

The `chart_container` renders a `canvas` element with a unique `id` that `Chart.js` targets during rendering. It handles responsiveness and accessibility and includes a `phx-hook` attribute that triggers client-side chart rendering. The container stores chart configuration in a `data-chart-config` attribute, while chart data is passed separately to individual charts rendered inside it.

The `chart` component renders a specific chart type with its associated data. It wraps `Chart.js` functionality so users can control their charts entirely through Elixir without writing JavaScript.

For reactive updates, a chart module must implement an `update/2` callback that responds to data changes and pushes events to the client. Here's an example:

```elixir
defmodule MyAppWeb.Component.Chart do
  use MyAppWeb, :live_component

  def render(assings) do
  ~H"""
    <.chart_container id={@id} config={@chart_config}>
      <.chart id={@id} type="line" data={@chart_data} />
    </.chart_container>
  """
  end

  def update(%{id: id, chart_data: chart_data} = assigns, socket) do
    socket =
      socket
      |> assign(assigns)
      |> push_event("update-chart-#{id}", %{chart_data: chart_data})

    {:ok, socket}
  end
end
```

And then on the client to handle the update event (this is a simplified example):

```js
Hooks.Chart = {
  mounted() {
    this.handleEvent(`update-chart-${this.el.id}`, chart_data => {
      const chart = this.el.chart
      chart.data = chart_data
      chart.update()
    });
  }
}
```

I propose creating a module that serves as an entry point for chart creation when users install the chart component. This module would contain all the necessary code for data handling, configuration, and chart rendering. Charts would begin with `use MyAppWeb.Component.Chart`, which injects the required functions into the component.

For example:

```elixir
defmodule MyAppWeb.MyChart do
  use MyAppWeb.Component.Chart

  def render(assigns) do
    ~H"""
    <.chart_container id={@id} config={@chart_config}>
      <.chart id={@id} type="line" data={@chart_data} />
    </.chart_container>
    """
  end
end
```

The `MyAppWeb.Component.Chart` module turns the module where it is used into a live_component, injects the `update/2` callback, imports the chart components, and sets up proper chart rendering. This way, users do not have to deal with JavaScript hooks and can build their charts using Elixir. Charts are reactive by default – they update automatically when data changes. Users can customize both `MyAppWeb.Component.Chart` and the JavaScript hook since they live in their projects.

Using a chart in a LiveView page would look like this:

```elixir
defmodule MyAppWeb.MyLivePage do
  use MyAppWeb, :live_view

  def mount(_params, _session, socket) do
    {:ok, socket
      |> assign(chart_config: %{})
      |> assign(chart_data: [%{x: 1, y: 1}, %{x: 2, y: 2}, %{x: 3, y: 3}])}
  end

  def render(assigns) do
    ~H"""
    <.live_component
    module={MyAppWeb.MyChart}
    id="my_chart"
    chart_config={@chart_config}
    chart_data={@chart_data}
    />
    """
  end
end
```
The configuration and chart data API will mostly follow the `Chart.js` API, adapting it to Elixir.

The chart data can be in any shape as long as it is a list of maps. It will be parsed against the chart configuration, in a similar way to how `shadcn ui` [handles it](https://ui.shadcn.com/docs/components/chart#your-first-chart). For customizing the chart itself, users can use the `Chart.js` API in their Elixir maps. It might be beneficial for both the chart data and the chart configuration to use snake_case for key names, which could then be automatically converted to camelCase when sent to the client.

This [post](https://medium.com/@lionel.aimerie/integrating-chart-js-into-elixir-phoenix-for-visual-impact-9a3991f0690f) contains examples of integrating `Chart.js` with Phoenix LiveView.

To use charts this way, users need to have `Chart.js` installed, along with the necessary hook to manage the chart's lifecycle. We can automate this by modifying the `salad.add` task to install `Chart.js` and copy the Chart hook to the user's project during the chart component installation.

That's it. I'd love to hear any thoughts regarding it. If this solution deemed appropiate, I will open a PR to implement it.

**Comment by bluzky** [comment]
I've never worked with chart in LiveView so chart is not in my original plan.  Thanks for spending time on this.
https://github.com/pnezis/tucan looks interesting. Have you tried it?

**Comment by selenil** [comment]
Thank you @bluzky. I wasn't aware of https://github.com/pnezis/tucan. I went through the docs, and it looks great. What I have in mind is a bit different, though—I'm proposing a reusable chart component that seamlessly integrates into existing Phoenix projects and leverages LiveView's features to dynamically update the chart as the data changes.

I already have a working implementation, and it's not too complex. If you'd like, I can open a PR for review.

Here's a quick demo:

https://github.com/user-attachments/assets/69ebd9cd-075f-49fd-a1d3-8b1859246980

**Comment by bluzky** [comment]
@selenil I have a PR to replace using macro, pls take a look #70

**Comment by bluzky** [comment]
completed with PR #67 #70 #72
