### ISSUE TITLE
An issue with opening a label example on SaladUI's website

### ISSUE THREAD

**Issue by zespere** [bluzky/salad_ui#65]
When i click "label" i get redirected to the separator's page, i assume that's not intended?

Update: there's also the same issue with checkbox and radio group

https://github.com/user-attachments/assets/0781950a-ff5c-4168-bc16-b6759475e7a4

**Comment by bluzky** [comment]
It could be issue with deployment to fly, It works perfect on my local machine. I tried rebuilding but nothing change. Hmm

**Comment by bluzky** [comment]
fixed, my naming error :D
