### ISSUE TITLE
Could not read file /app/assets/tailwind.colors.json - tails.ex

### ISSUE THREAD

**Issue by ashkan117** [bluzky/salad_ui#7]
Hello,

Love the work on this project! The components like tooltip and the dropdown are exactly what I needed so I'm testing this out in my project. It seems to work locally but if I try and deploy I get this error

```bash
== Compilation error in file lib/tails.ex ==
** (File.Error) could not read file "/app/assets/tailwind.colors.json": no such file or directory
     (elixir 1.15.7) lib/file.ex:358: File.read!/1
     lib/tails.ex:3: (module)
```

Do you have any advice on what I can check?

**Comment by ashkan117** [comment]
The issue was now the compile step depends on the assets due to the `tails` library. I updated my dockerfile to move step that copies the assets to before the compile step

```bash
# dockerfile
COPY assets assets
RUN mix deps.compile
```

**Comment by ashkan117** [comment]
This does result in a different error though

**Comment by bluzky** [comment]
@ashkan117 salad_ui depends on another package for css animation

```
cd assets
npm i -D tailwindcss-animate
# or yarn
yarn add -D tailwindcss-animate
```

**Comment by ashkan117** [comment]
I think I do that in my deployment setup. 

```bash
#package.json
{
  "devDependencies": {
    "tailwindcss-animate": "^1.0.7"
  },
}
```

And in my Dockerfile I do `npm install`

**Comment by ashkan117** [comment]
I think the issue was that `npm install` does not install dev dependencies in my case
So the following steps ended up fixing things for me

```bash
# Copy assets before running deps.compile
COPY assets assets
RUN mix deps.compile
```

```bash

# Install the animate dependency before assets.deploy
RUN cd assets && npm i -D tailwindcss-animate
```
