### ISSUE TITLE
dependency error warning with versions

### ISSUE THREAD

**Issue by bluejack** [bluzky/salad_ui#73]
Using Hex v 0.11.0 there is a warning somewhere about a dependency error that visual studio provides non-specific errors about.

My project runs fine, but I am confused about where this error is coming from. It blocks all developer tools from doing things like syntax highlighting, etc. This could be a problem with visual studio or one of the elixir extensions, but it is 100% reproducible and traceable to the difference between 0.5.1 and 0.6.0:

```
an exception was raised:
    ** (Mix.Error) Can't continue due to errors on dependencies
        (mix 1.17.2) lib/mix.ex:588: Mix.raise/2
        (mix 1.17.2) lib/mix/tasks/deps.loadpaths.ex:48: Mix.Tasks.Deps.Loadpaths.run/1
        (mix 1.17.2) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
        (mix 1.17.2) lib/mix/tasks/loadpaths.ex:37: Mix.Tasks.Loadpaths.run/1
        (mix 1.17.2) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
        (mix 1.17.2) lib/mix/tasks/compile.ex:153: Mix.Tasks.Compile.run/1
        (mix 1.17.2) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
        (language_server 0.24.1) lib/language_server/build.ex:442: ElixirLS.LanguageServer.Build.run_mix_compile/1
        (language_server 0.24.1) lib/language_server/build.ex:80: anonymous fn/3 in ElixirLS.LanguageServer.Build.build/3
        (stdlib 5.2.3) timer.erl:270: :timer.tc/2
        (language_server 0.24.1) lib/language_server/build.ex:20: anonymous fn/3 in ElixirLS.LanguageServer.Build.build/3
        (kernel 9.2.4) global.erl:477: :global.trans/4
```

*UPDATE*:

The problem happens in elixir-ls. I don't know *why* it happens in elixir-ls for this version upgrade, but here is the solution:

1. Stop your IDE/editor including the elixir LSP.
2. Kill any left-over elixir/elixir-ls processes. (This was important.) Find them via e.g. procs elixir or ps axu | grep elixir.
3. In your project directory: rm -rf .elixir_ls _build mix.lock && mix deps.get.
4. Restart your IDE/editor including the elixir LSP.

**Comment by bluzky** [comment]
Sounds weird. I didn't update any dependency.
Thanks for report the issue and give the solution. I'll keep it here for a while, in case someone has the same issue.
