### ISSUE TITLE
Accordion question - updating data

### ISSUE THREAD

**Issue by bluejack** [bluzky/salad_ui#75]
If I update an accordion contents, the liveview state refreshes. Is there a way to dynamically enforce the opening of a specific accordion value? Or is there something else I might be doing wrong here?

**Comment by bluzky** [comment]
@bluejack I've just added `open` to enforce state open. When I implemented it, I only think of the case where user use Accordion statically :D.

This will be available in release `v0.12.0`

```heex
          <.accordion_item>
            <.accordion_trigger group="my-group" open>
              Is it accessible?
            </.accordion_trigger>
            <.accordion_content>
              Yes. It adheres to the WAI-ARIA design pattern.
            </.accordion_content>
          </.accordion_item>
```
