### ISSUE TITLE
Tails is deprecated

### ISSUE THREAD

**Issue by eugkhp** [bluzky/salad_ui#79]
After installing the dependency I went to check what is tails and found it was deprecated

https://github.com/zachdaniel/tails

**Comment by bluzky** [comment]
Yes, I read the thread on [Elixir forum](https://elixirforum.com/t/turboprop-toolkit-to-create-accessible-component-libraries/64228/17). He just did soft deprecated. 
Sadly, `Turboprop` was archived 😢.
In the meantime, I haven't found any alternative solution, so still keep using tails.

Do you have any suggestion @eugkhp?

**Comment by eugkhp** [comment]
I'm not entirely sure, is it even necessary?

**Comment by bluzky** [comment]
It is surely necessary to merge tailwind class. For example, default class is `bg-red` and you pass custom `class="bg-green"`, without `tails` not always it renders green background. `tails` make sure only `bg-green` exists in final class list

**Comment by bluzky** [comment]
I'm working to remove `tails` in #84
