### ISSUE TITLE
Integrate lucide component 

### ISSUE THREAD

**Issue by mrdotb** [bluzky/salad_ui#8]
Hello,

I'm not sure where to put it yet, but here is a recipe for adding the Lucide components in a similar fashion to the Hero components. I am happy to help document this part.

https://gist.github.com/mrdotb/8b78fde7dc3c8e191d1c8a4b90e21b0f

**Comment by bluzky** [comment]
@mrdotb thanks for your suggestion. I think SaladUI should not depend on any icon library, so developers can use whatever they want.

**Comment by mrdotb** [comment]
I did not mean to add any dependencies. Instead, I intended it to be more like a guide. Since shadcdn uses Radix Icon or Lucide components, I thought documenting this part would be useful.

**Comment by bluzky** [comment]
> I did not mean to add any dependencies. Instead, I intended it to be more like a guide. Since shadcdn uses Radix Icon or Lucide components, I thought documenting this part would be useful.

That's great. So please add guide to integrate Lucide icon.
