### ISSUE TITLE
Named slots

### ISSUE THREAD

**Issue by torepettersen** [bluzky/salad_ui#82]
Hi, and thanks for your amazing work on this library. LiveView really needed a good component library and I feel Salad UI, is exactly what I was hoping for.

I am just curios why named slots was not used, but instead components inside components. Was it just because shadcn does it like that and it was copied without giving it much tought? Or are there other reasons?

Just curios since, since I am considering moving my copies of the components to use named slots, since I find that looks cleaner.

Example with the popover. I tried to convert that and I noticed that it got a bit easier to use, since I could hide the ID and target without having to pass them to both the trigger and the content. I myself used a bit of time to understand why it was not working, since it didn't pass the correct ID and target to the context and trigger the first time I tried using this component :sweat_smile:
``` 
<.popover side="left">
  <:trigger>
    <.button variant="link">
      @salad_ui
    </.button>
  </:trigger>

  <:content class="p-0">
    Hover card content
  </:content>
</.popover>
```

With this much work done, I guess it might be to late to rewrite it all to use names slots :sweat_smile:  But I am really curios on your opinon it.

And thanks again for your amazing work on this library :heart:

**Comment by bluzky** [comment]
@torepettersen thanks for your opinion. I chose tag instead of slot because of some reasons:
1. there are many nested components and slot doesn't support that use case. 
2. separating into multiple function component make maintenance easier
3. and it's easier to write unit test for each function component than slot
4. function component help to maximize customization capability: you can arrange order of components, custom class, attribute, ..

For example, with slot it's impossible to implement menu item like this:
```heex
       <.menu_group>
            <.menu_item>
              <.icon name="hero-user" class="mr-2 h-4 w-4" />
              <span>Profile</span>
              <.menu_shortcut>⌘P</.menu_shortcut>
            </.menu_item>
            <.menu_item>
              <.icon name="hero-banknotes" class="mr-2 h-4 w-4" />
              <span>Billing</span>
              <.menu_shortcut>⌘B</.menu_shortcut>
            </.menu_item>
            <.menu_item>
              <.icon name="hero-cog-6-tooth" class="mr-2 h-4 w-4" />
              <span>Settings</span>
              <.menu_shortcut>⌘S</.menu_shortcut>
            </.menu_item>
          </.menu_group>
```

**Comment by torepettersen** [comment]
Thank you for taking the time to give me such a detailed answer. Seems like you already put a lot of though into it 😊

Seems like named slots are a bit more limiting than I was aware of. Also noticed they don't support rest/global attributes.

So you have to give up a bit, for a slightly nicer API, in a few cases. Or maybe there are other ways around that without using named slots, to make a similar nice API? I will let you know if I can think of something.

And close the ticket since your answer more than answers my question 😊
