### ISSUE TITLE
Internal Server Error on the form section of the demo StoryBook

### ISSUE THREAD

**Issue by dustinaleksiuk** [bluzky/salad_ui#86]
When I navigate to https://salad-storybook.fly.dev/salad_ui_component/form, I get an Internal Server Error. Other pages seem to work fine.

I cloned the main repo and the storybook repo to try to take a look, but I think there are some steps missing in the instructions. I get a number of errors when I try to start it.

The library is looking great!

**Comment by bluzky** [comment]
Thank you, maybe some recent change cause this issue.

**Comment by bluzky** [comment]
this issue has been fix, thanks
