### ISSUE TITLE
[NOT ISSUE] - Site search with modal and combobox example code

### ISSUE THREAD

**Issue by kuatroka** [bluzky/salad_ui#95]
Hi, the saladui's page got a site search functionality that use the button, comobobox and modal. Could anyone point me to the code that powers it up? I couldn't find it in the list of examples/components. See the gif. Thanks

![combo_modal](https://github.com/user-attachments/assets/cb0aab6b-e225-4ed8-990c-53244b3a989f)

**Comment by bluzky** [comment]
Hi @kuatroka it's the function of Phoenix Storybook. You can see it here https://github.com/phenixdigital/phoenix_storybook/blob/main/lib/phoenix_storybook/live/search.ex

**Comment by kuatroka** [comment]
Thanks, I'll see how I can repurpose it for my case and hook up my data to it.
